"""Append-only audit log with hash chaining (v6 Section 15.5).

previous_hash/sequence_number are derived fresh from the DB on every call,
under an in-process lock -- not cached in memory. An earlier version
cached the chain head in a module global, which broke as soon as a
second process touched the same DB file (e.g. `python -m backend.seed`
run once while `uvicorn` is already up): the running server's cached
sequence number went stale and the next audit write collided on the
sequence_number UNIQUE constraint. Re-deriving from the DB avoids that;
the lock still prevents two threads *within this process* (the request
thread and the background job-worker thread) from racing between the
read and the insert -- which requires this function to commit before
releasing the lock (see below), since every caller uses its own session
and an uncommitted flush on one connection is invisible to a concurrent
reader on another; releasing the lock any earlier would let a second
thread read the same "last row" and fork the chain.

This still assumes one writer process at a time in practice -- two
processes truly racing at the database level could still collide -- but
that's an accepted gap for a hackathon SQLite deployment (plan decision
#4), not something this module tries to solve generally.
"""

import hashlib
import json
import threading
import uuid
from datetime import datetime, timezone

from sqlalchemy import select
from sqlalchemy.orm import Session

from backend.db.models import AuditLog

# Stand-in actor identity for events generated by the background worker /
# retention job rather than a logged-in user (e.g. case_analysis_completed,
# dlq_entry_created). actor_id has no FK to users -- it's a plain UUID --
# so this never needs a matching row.
SYSTEM_ACTOR_ID = uuid.UUID(int=0)
SYSTEM_ACTOR_ROLE = "system"

_lock = threading.Lock()


def _hash_row(
    actor_id: uuid.UUID,
    actor_role: str,
    event_type: str,
    event_timestamp: datetime,
    case_id: uuid.UUID | None,
    request_id: uuid.UUID | None,
    previous_hash: str | None,
) -> str:
    # SQLite drops tzinfo on round-trip (DateTime(timezone=True) is a no-op
    # there); every event_timestamp this module creates is UTC, so a naive
    # value read back from the DB is re-anchored to UTC before hashing,
    # otherwise verify_chain() would never match what was hashed at insert
    # time.
    if event_timestamp.tzinfo is None:
        event_timestamp = event_timestamp.replace(tzinfo=timezone.utc)

    payload = {
        "actor_id": str(actor_id),
        "actor_role": actor_role,
        "event_type": event_type,
        "event_timestamp": event_timestamp.isoformat(),
        "case_id": str(case_id) if case_id else None,
        "request_id": str(request_id) if request_id else None,
        "previous_hash": previous_hash,
    }
    return hashlib.sha256(json.dumps(payload, sort_keys=True).encode("utf-8")).hexdigest()


def record_audit_event(
    session: Session,
    *,
    actor_id: uuid.UUID,
    actor_role: str,
    event_type: str,
    case_id: uuid.UUID | None = None,
    request_id: uuid.UUID | None = None,
) -> AuditLog:
    with _lock:
        last_row = session.execute(
            select(AuditLog).order_by(AuditLog.sequence_number.desc())
        ).scalars().first()
        previous_hash = last_row.metadata_hash if last_row else None
        sequence_number = (last_row.sequence_number + 1) if last_row else 0

        event_timestamp = datetime.now(timezone.utc)
        metadata_hash = _hash_row(
            actor_id, actor_role, event_type, event_timestamp, case_id, request_id, previous_hash
        )

        row = AuditLog(
            case_id=case_id,
            actor_id=actor_id,
            actor_role=actor_role,
            event_type=event_type,
            event_timestamp=event_timestamp,
            request_id=request_id,
            metadata_hash=metadata_hash,
            previous_hash=previous_hash,
            sequence_number=sequence_number,
        )
        session.add(row)
        session.flush()
        # Commit while still holding the lock -- every caller invokes this as
        # its last step before its own (now redundant, harmless) commit, so
        # this doesn't change any caller's atomicity. See the module
        # docstring: without this, a second thread could acquire the lock,
        # read the same not-yet-committed "last row" from its own session,
        # and fork the chain.
        session.commit()
        return row


def verify_chain(session: Session) -> bool:
    """Re-derives every row's hash in insertion order and checks linkage.

    Intended for the Auditor role / tests, not the request hot path.
    """
    rows = session.execute(
        select(AuditLog).order_by(AuditLog.sequence_number)
    ).scalars().all()

    expected_previous: str | None = None
    for row in rows:
        if row.previous_hash != expected_previous:
            return False
        recomputed = _hash_row(
            row.actor_id, row.actor_role, row.event_type, row.event_timestamp, row.case_id, row.request_id, row.previous_hash
        )
        if recomputed != row.metadata_hash:
            return False
        expected_previous = row.metadata_hash

    return True